/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MainController;

/**
 *
 * @author Usuario
 */
public class ConexaoView extends javax.swing.JFrame {

    MainController controller = null;

    /**
     * Creates new form ConexaoView
     */
    public ConexaoView() {
        initComponents();
    }

    public ConexaoView(MainController client) {
        controller = client;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insiraPorta = new javax.swing.JLabel();
        tfPorta = new javax.swing.JTextField();
        btSalva = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        insiraNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        insiraPorta.setText("Insira a porta:");

        tfPorta.setToolTipText("ex: 8000");
        tfPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPortaActionPerformed(evt);
            }
        });

        btSalva.setText("Vamos lá");
        btSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaActionPerformed(evt);
            }
        });

        tfNome.setToolTipText("ex: Ronaldo Fenomeno Copa 92");
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        insiraNome.setText("Insira seu nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(insiraPorta)
                                        .addComponent(tfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 265,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addComponent(btSalva))
                                        .addComponent(insiraNome)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 265,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(18, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(insiraPorta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPorta, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18,
                                        Short.MAX_VALUE)
                                .addComponent(insiraNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btSalva)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfNomeActionPerformed

    private void btSalvaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSalvaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btSalvaActionPerformed

    private void tfPortaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfPortaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfPortaActionPerformed

    private void btSalvaPortaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSalvaPortaActionPerformed

        // verifica se a porta esta vazia ou zoada
        if (!tfPorta.getText().isEmpty() && tfPorta.getText().matches("[+-]?\\d*(\\.\\d+)?")
                && !tfNome.getText().isEmpty()) {

            controller.criarUsuario(tfNome.getText(), Integer.parseInt(tfPorta.getText()));
            // controller.definirPorta(Integer.parseInt(tfPorta.getText()));

            PrincipalView pv = new PrincipalView(Integer.parseInt(tfPorta.getText()), controller);
            pv.setTitle(tfPorta.getText());
            this.dispose();
            pv.setVisible(true);

        }
    }// GEN-LAST:event_btSalvaPortaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexaoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexaoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexaoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexaoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexaoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalva;
    private javax.swing.JLabel insiraNome;
    private javax.swing.JLabel insiraPorta;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPorta;
    // End of variables declaration//GEN-END:variables
}
